onlyBuiltDependencies:
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd
  - "@tailwindcss/oxide"
  - "dtrace-provider"

packages:
  - "mcp-b-extension"
  - "web"
  - "packages/*"
  - "e2e-tests"

catalog:
  # Formatting & Linting
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0
  eslint: ^9.17.0
  prettier: ^3.4.2

  # TypeScript & Types
  typescript: ^5.8.3
  "@types/node": ^22.15.21
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@types/chrome": ^0.0.326

  # Build Tools
  tsup: ^8.4.0
  tsx: ^4.20.0

  # Core Dependencies
  "@modelcontextprotocol/sdk": ^1.3.0
  zod: ^3.25.64
  dotenv: ^16.5.0

  # React & UI
  react: ^19.1.0
  react-dom: ^19.1.0

  # AI/Assistant SDKs
  "@ai-sdk/openai": ^1.3.16
  "@ai-sdk/google": ^1.2.21
  ai: ^4.3.9
  "@anthropic-ai/sdk": ^0.54.0
  "@assistant-ui/react": ^0.10.24
  "@assistant-ui/react-ai-sdk": ^0.10.14
  "@assistant-ui/react-hook-form": ^0.10.5
  "@assistant-ui/react-markdown": ^0.10.2

  # Forms
  react-hook-form: ^7.57.0
  "@hookform/resolvers": ^5.0.1

  # UI/Styling
  tailwindcss: ^4.1.7
  tailwind-merge: ^3.2.0
  clsx: ^2.1.1
  lucide-react: ^0.503.0
  remark-gfm: ^4.0.1

  # Testing
  playwright: ^1.53.0
  "@playwright/test": ^1.53.0

  # Other Common Dependencies
  cheerio: ^1.1.0
  "@types/json-schema": ^7.0.15
